# Generated by Django 2.0.5 on 2021-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recup',
            name='nbfois',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (3, 4)], verbose_name='Combien de fois avez vous manquez votre examen ?'),
        ),
    ]
